version: '3.4'

services:
  andaha.gateways.ocelot:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      Hosts__OCELOT_DAPR_SIDECAR: http://127.0.0.1:3500
    ports:
      - "9000:80"
      - "50001:50001"

  andaha.gateways.ocelot.dapr:
    command: [
      "./daprd",
      "--app-id", "ocelot-gateway",
      "--app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr.placement:50000"
    ]

  andaha.services.identity:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__ApplicationDbConnection: Server=andaha.services.identity.db;Database=andaha-identity-db;User Id=sa;Password=Pass@word;Encrypt=false
      IssuerUrl: http://localhost:9100
      ExternalUrls__ShoppingApi: http://andaha.services.shopping:80
      ExternalUrls__CollaborationApi: http://andaha.services.collaboration:80
      ExternalUrls__BudgetplanApi: http://andaha.services.budgetplan:80
      ExternalUrls__MonolithApi: http://andaha.services.monolith:80
      ExternalUrls__WebMiniClient: http://localhost:4200
      Authentication__Facebook__AppId: ${AUTH_FACEBOOK_APP_ID}
      Authentication__Facebook__AppSecret: ${AUTH_FACEBOOK_APP_SECRET}
      Authentication__Google__ClientId: ${AUTH_GOOGLE_CLIENT_ID}
      Authentication__Google__ClientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
    ports:
      - "9100:80"

  andaha.services.identity.dapr:
    command: [
      "./daprd",
      "-app-id", "identity-api",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr.placement:50000",
    ]

  andaha.services.identity.db:
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@word
    ports:
      - "9110:1433" 
    volumes:
      - ./volumes/identitysqlvolume:/var/opt/mssql/data

  andaha.services.shopping:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__ApplicationDbConnection: Server=andaha.services.shopping.db;Database=andaha-shopping-db;User Id=sa;Password=Pass@word;Encrypt=false
      ExternalUrls__IdentityApi: http://andaha.services.identity:80
      Dapr__CollaborationAppId: collaboration-api
      Authentication__AzureAdB2C__Instance: ${AUTH_B2C_INSTANCE}
      Authentication__AzureAdB2C__ClientId: ${AUTH_B2C_CLIENTID}
      Authentication__AzureAdB2C__Domain: ${AUTH_B2C_DOMAIN}
      Authentication__AzureAdB2C__TenantId: ${AUTH_B2C_TENANTID}
      Authentication__AzureAdB2C__SignUpSignInPolicyId: ${AUTH_B2C_POLICY}
      Authentication__AzureAdB2CSwagger__Tenant: ${AUTH_B2CSWAGGER_TENANT}
      Authentication__AzureAdB2CSwagger__SignUpSignInPolicyId: ${AUTH_B2CSWAGGER_POLICY}
      Authentication__AzureAdB2CSwagger__ClientId: ${AUTH_B2CSWAGGER_CLIENTID}
      Authentication__AzureAdB2CSwagger__Scope: ${AUTH_B2CSWAGGER_SCOPE}
    ports:
      - "9200:80"

  andaha.services.shopping.dapr:
    command: [
      "./daprd",
      "-app-id", "shopping-api",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr.placement:50000",
    ]

  andaha.services.shopping.db:
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@word
    ports:
      - "9210:1433"
    volumes:
      - ./volumes/shoppingsqlvolume:/var/opt/mssql/data

  andaha.services.collaboration:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__ApplicationDbConnection: Server=andaha.services.collaboration.db;Database=andaha-collaboration-db;User Id=sa;Password=Pass@word;Encrypt=false
      Authentication__AzureAdB2C__Instance: ${AUTH_B2C_INSTANCE}
      Authentication__AzureAdB2C__ClientId: ${AUTH_B2C_CLIENTID}
      Authentication__AzureAdB2C__Domain: ${AUTH_B2C_DOMAIN}
      Authentication__AzureAdB2C__TenantId: ${AUTH_B2C_TENANTID}
      Authentication__AzureAdB2C__SignUpSignInPolicyId: ${AUTH_B2C_POLICY}
      Authentication__AzureAdB2CSwagger__Tenant: ${AUTH_B2CSWAGGER_TENANT}
      Authentication__AzureAdB2CSwagger__SignUpSignInPolicyId: ${AUTH_B2CSWAGGER_POLICY}
      Authentication__AzureAdB2CSwagger__ClientId: ${AUTH_B2CSWAGGER_CLIENTID}
      Authentication__AzureAdB2CSwagger__Scope: ${AUTH_B2CSWAGGER_SCOPE}
      Authentication__AzureAdB2CGraphApi__TenantId: ${AUTH_B2CGRAPH_TENANTID}
      Authentication__AzureAdB2CGraphApi__ClientId: ${AUTH_B2CGRAPH_CLIENTID}
      Authentication__AzureAdB2CGraphApi__ClientSecret: ${AUTH_B2CGRAPH_CLIENTSECRET}
    ports:
      - "9300:80"

  andaha.services.collaboration.dapr:
    command: [
      "./daprd",
      "-app-id", "collaboration-api",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr.placement:50000",
    ]

  andaha.services.collaboration.db: 
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@word
    ports:
      - "9310:1433"
    volumes:
      - ./volumes/collaborationsqlvolume:/var/opt/mssql/data
  
  andaha.services.budgetplan:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__ApplicationDbConnection: Server=andaha.services.budgetplan.db;Database=andaha-budgetplan-db;User Id=sa;Password=Pass@word;Encrypt=false
      Dapr__CollaborationAppId: collaboration-api
      Authentication__AzureAdB2C__Instance: ${AUTH_B2C_INSTANCE}
      Authentication__AzureAdB2C__ClientId: ${AUTH_B2C_CLIENTID}
      Authentication__AzureAdB2C__Domain: ${AUTH_B2C_DOMAIN}
      Authentication__AzureAdB2C__TenantId: ${AUTH_B2C_TENANTID}
      Authentication__AzureAdB2C__SignUpSignInPolicyId: ${AUTH_B2C_POLICY}
      Authentication__AzureAdB2CSwagger__Tenant: ${AUTH_B2CSWAGGER_TENANT}
      Authentication__AzureAdB2CSwagger__SignUpSignInPolicyId: ${AUTH_B2CSWAGGER_POLICY}
      Authentication__AzureAdB2CSwagger__ClientId: ${AUTH_B2CSWAGGER_CLIENTID}
      Authentication__AzureAdB2CSwagger__Scope: ${AUTH_B2CSWAGGER_SCOPE}
    ports:
      - "9400:80"

  andaha.services.budgetplan.dapr:
    command: [
      "./daprd",
      "-app-id", "budgetplan-api",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr.placement:50000",
    ]

  andaha.services.budgetplan.db:
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@word
    ports:
      - "9410:1433"
    volumes:
      - ./volumes/budgetplansqlvolume:/var/opt/mssql/data

  andaha.services.monolith:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__ApplicationDbConnection: Server=andaha.services.monolith.db;Database=andaha-monolith-db;User Id=sa;Password=Pass@word;Encrypt=false
      Dapr__CollaborationAppId: monolith-api
      Authentication__AzureAdB2C__Instance: ${AUTH_B2C_INSTANCE}
      Authentication__AzureAdB2C__ClientId: ${AUTH_B2C_CLIENTID}
      Authentication__AzureAdB2C__Domain: ${AUTH_B2C_DOMAIN}
      Authentication__AzureAdB2C__TenantId: ${AUTH_B2C_TENANTID}
      Authentication__AzureAdB2C__SignUpSignInPolicyId: ${AUTH_B2C_POLICY}
      Authentication__AzureAdB2CSwagger__Tenant: ${AUTH_B2CSWAGGER_TENANT}
      Authentication__AzureAdB2CSwagger__SignUpSignInPolicyId: ${AUTH_B2CSWAGGER_POLICY}
      Authentication__AzureAdB2CSwagger__ClientId: ${AUTH_B2CSWAGGER_CLIENTID}
      Authentication__AzureAdB2CSwagger__Scope: ${AUTH_B2CSWAGGER_SCOPE}
      Authentication__AzureAdB2CGraphApi__TenantId: ${AUTH_B2CGRAPH_TENANTID}
      Authentication__AzureAdB2CGraphApi__ClientId: ${AUTH_B2CGRAPH_CLIENTID}
      Authentication__AzureAdB2CGraphApi__ClientSecret: ${AUTH_B2CGRAPH_CLIENTSECRET}
    ports:
      - "9900:80"

  andaha.services.monolith.dapr:
    command: [
      "./daprd",
      "-app-id", "monolith-api",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr.placement:50000",
    ]

  andaha.services.monolith.db:
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@word
    ports:
      - "9910:1433"
    volumes:
      - ./volumes/monolithsqlvolume:/var/opt/mssql/data

  dapr.placement:
    command: ["./placement", "--port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  andaha.webapps.servicestatus:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      HealthChecksUI__HealthChecks__0__Name: Identity Service
      HealthChecksUI__HealthChecks__0__Uri: http://andaha.services.identity/hc
      HealthChecksUI__HealthChecks__1__Name: Shopping Service
      HealthChecksUI__HealthChecks__1__Uri: http://andaha.services.shopping/hc
      HealthChecksUI__HealthChecks__2__Name: Collaboration Service
      HealthChecksUI__HealthChecks__2__Uri: http://andaha.services.collaboration/hc
    ports:
      - "10000:80"