version: '3.4'

services:
  andaha.gateways.ocelot:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      Hosts__SHOPPING_API_HOST: http://andaha.services.shopping:80
    ports:
      - "9000:80"

  andaha.services.identity:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__ApplicationDbConnection: Server=andaha.services.identity.db;Database=andaha-identity-db;User Id=sa;Password=Pass@word;
      ExternalUrls__ShoppingApi: http://andaha.services.shopping:80
    ports:
      - "9100:80"

  andaha.services.identity.db:
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: Pass@word
      ports:
        - "9110:1433" 

  andaha.services.shopping:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__ApplicationDbConnection: Server=andaha.services.shopping.db;Database=andaha-shopping-db;User Id=sa;Password=Pass@word;
      ExternalUrls__IdentityApi: http://andaha.services.identity:80
    ports:
      - "9200:80"

  andaha.services.shopping.db:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@word
    ports:
      - "9210:1433"     
