trigger:
  batch: true
  branches:
    include:
      - master
      - feature/webapps/miniclient/*
  paths:
    include:
    - src/WebApps/MiniClient/*

pool:
  vmImage: "ubuntu-latest"

variables:
  nodeModulesCachePath: $(System.DefaultWorkingDirectory)/src/WebApps/MiniClient/Andaha.WebApps.MiniClient/node_modules

steps:
  - task: Cache@2
    displayName: "cache npm packages"
    inputs:
      key: 'npm | "$(Agent.OS)" | src/WebApps/MiniClient/Andaha.WebApps.MiniClient/package-lock.json'
      restoreKeys: 'npm | "$(Agent.OS)"'
      path: "$(nodeModulesCachePath)"
      cacheHitVar: CACHE_RESTORED

  - task: Npm@1
    displayName: "install typescript"
    inputs:
      command: custom
      verbose: false
      customCommand: "install -D typescript"

  - task: Npm@1
    displayName: "npm install"
    condition: ne(variables.CACHE_RESTORED, 'true')
    inputs:
      command: custom
      workingDir: src/WebApps/MiniClient/Andaha.WebApps.MiniClient
      verbose: false
      customCommand: install --force

  - task: Npm@1
    displayName: "npm build"
    inputs:
      command: custom
      workingDir: src/WebApps/MiniClient/Andaha.WebApps.MiniClient
      verbose: false
      customCommand: run build
