trigger:
  branches:
    include:
      - master

pool:
  vmImage: "windows-latest"

variables:
  azureServiceConnection: "azure-rm-andaha-dev-connection"
  containerRegistryConnection: "azure-container-reg-dev-connection"

stages:
- stage: CI
  displayName: CI
  jobs: 
  - job: build_and_publish_services
    steps:
    - task: NuGetToolInstaller@1

    - task: Docker@2
      displayName: Service Shopping - build and push image
      inputs:
        command: buildAndPush
        dockerfile: $(Build.SourcesDirectory)/src/Services/Andaha.Services.Shopping/Dockerfile
        containerRegistry: $(containerRegistryConnection)
        tags: ${Build.BuildId}

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact"
