trigger:
  batch: true
  branches:
    include:
      - master
      - feature/identity/*
  paths:
    include:
    - src/Services/Identity/*

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: NuGetToolInstaller@1

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET7'
    inputs:
      packageType: sdk
      version: 7.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: '**/Andaha.Services.Identity.csproj'

  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command: "build"
      projects: '**/Andaha.Services.Identity.csproj'
      arguments: "--configuration $(BuildConfiguration)"
