trigger:
  branches:
    include:
      - release/gateway/ocelot/v*
      - refs/release/gateway/ocelot/v*

pool:
  vmImage: "ubuntu-latest"

variables:
  containerRegistryConnection: "andaha-container-reg-connection"
  imageTag: "$(Build.SourceBranchName)"
  bicepTemplateFile: "src/ApiGateways/Ocelot/pipeline/bicep/ocelot-main.bicep"

name: "$(Build.SourceBranchName)"

stages:
- stage: build
  displayName: Build
  jobs:
    - job: build_and_push_image
      steps:
      - task: Docker@2
        displayName: build image
        inputs:
          command: buildAndPush
          dockerfile: src/ApiGateways/Ocelot/Andaha.ApiGateways.Ocelot/Dockerfile
          repository: andaha/gateways/ocelot
          containerRegistry: $(containerRegistryConnection)
          tags: |
            $(imageTag)
            latest

- stage: deploy_dev
  displayName: Deploy to dev
  dependsOn: build
  jobs:
  - job: deployment
    steps:
    - task: AzureCLI@2
      displayName: 'Infrastructure provisioning'
      inputs:
        azureSubscription: $(azureDevServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          acrUser=$(az acr credential show --name andaha --resource-group andaha --query username -o tsv)
          acrPassword=$(az acr credential show --name andaha --resource-group andaha --query "passwords[0].value" -o tsv)
          az deployment group create --resource-group andaha-dev --template-file $(bicepTemplateFile) --parameters stage="dev" containerRegistryUsername="$acrUser" containerRegistryPassword="$acrPassword" version="$(Build.SourceBranchName)" sqlServerAdminPassword=$(sqlServerAdminPassword)

- stage: deploy_prod
  displayName: Deploy to prod
  dependsOn: deploy_dev
  condition: succeeded()
  jobs:
  - deployment: deploy_prod
    displayName: Approval for prod
    environment: Production
  - job: deployment
    steps:
    - task: Docker@2
      displayName: build image
      inputs:
        command: buildAndPush
        dockerfile: src/ApiGateways/Ocelot/Andaha.ApiGateways.Ocelot/Dockerfile
        repository: prod/andaha/gateways/ocelot
        containerRegistry: $(containerRegistryConnection)
        tags: |
          $(imageTag)
          latest

    - task: AzureCLI@2
      displayName: 'Infrastructure provisioning'
      inputs:
        azureSubscription: $(azureProdServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          acrUser=$(az acr credential show --name andaha --resource-group andaha --query username -o tsv)
          acrPassword=$(az acr credential show --name andaha --resource-group andaha --query "passwords[0].value" -o tsv)
          az deployment group create --resource-group andaha-prod --template-file $(bicepTemplateFile) --parameters stage="prod" containerRegistryUsername="$acrUser" containerRegistryPassword="$acrPassword" version="$(Build.SourceBranchName)" sqlServerAdminPassword=$(sqlServerAdminPassword)
