trigger:
  batch: true
  branches:
    include:
      - master
      - feature/collaboration/*
  paths:
    include:
    - src/Services/Collaboration/*

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"
  nugetFeed: "andaha/andaha-feed"

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET7'
    inputs:
      packageType: sdk
      version: 7.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      feedRestore: $(nugetFeed)
      projects: '**/Andaha.Services.Collaboration.csproj'

  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command: "build"
      projects: '**/Andaha.Services.Collaboration.csproj'
      arguments: "--configuration $(BuildConfiguration)"
