trigger:
  batch: true
  branches:
    include:
      - master
      - feature/collaboration/*
  paths:
    include:
    - src/Services/Collaboration/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: Development
  containerRegistryConnection: "andaha-container-reg-connection"

steps:
  - task: Docker@2
    displayName: build image
    inputs:
      command: build
      arguments: '--build-arg PatPlaceholder=$(nugetFeedAccessToken)'
      dockerfile: src/Services/Collaboration/Andaha.Services.Collaboration/Dockerfile
      repository: andaha/services/collaboration
      containerRegistry: $(containerRegistryConnection)
      tags: |
        $(imageTag)
        latest
