trigger:
  batch: true
  branches:
    include:
      - release/shopping/v*
      - refs/release/shopping/v*
      - master
      - feature/shopping/*
  paths:
    include:
    - /src/shipping/shopping

pool:
  vmImage: "windows-latest"

variables:
  containerRegistryConnection: "azure-container-reg-dev-connection"

stages:
- stage: CI
  displayName: CI Shopping Service
  jobs: 
  - job: build_and_push_service
    steps:
    - task: Docker@2
      displayName: build and push image
      inputs:
        command: buildAndPush
        dockerfile: ../Dockerfile
        containerRegistry: $(containerRegistryConnection)
        tags: ${Build.BuildId}