trigger:
  branches:
    include:
      - release/shopping/v*
      - refs/release/shopping/v*

pool:
  vmImage: "windows-latest"

variables:
  containerRegistryConnection: "azure-container-reg-dev-connection"
  imageTag: "$(Build.SourceBranchName)"

steps:
- task: Docker@2
  displayName: build image
  inputs:
    command: build
    arguments: '--build-arg PatPlaceholder=$(NugetFeedAccessToken)'
    dockerfile: src/Services/Andaha.Services.Shopping/Dockerfile
    repository: andaha/services/shopping
    containerRegistry: $(containerRegistryConnection)
    tags: $(imageTag)
    
- task: Docker@2
  displayName: push image
  inputs:
    command: push
    dockerfile: src/Services/Andaha.Services.Shopping/Dockerfile
    repository: andaha/services/shopping
    containerRegistry: $(containerRegistryConnection)
    tags: $(imageTag)