trigger:
  branches:
    include:
      - release/shopping/v*
      - refs/release/shopping/v*

pool:
  vmImage: "windows-latest"

variables:
  containerRegistryConnection: "azure-container-reg-dev-connection"
  imageTag: "$(Major).$(Minor).$(Patch)"
  branchName: "$(Build.SourceBranchName)"

steps:
- task: PowerShell@2
  displayName: set major version
  inputs:
    targetType: inline
    script: |
      [string] $majorVersion = "$(branchName)".SubString(1, "$(branchName)".IndexOf(".") - 1)
      Write-Host "Set major version to '$majorVersion'"
      Write-Host "##vso[task.setvariable variable=Major]$majorVersion"

- task: PowerShell@2
  displayName: set minor version
  inputs:
    targetType: inline
    script: |
      [string] $minorVersion = "$(branchName)".SubString("$(branchName)".IndexOf(".") + 1).SubString(0, "$(branchName)".IndexOf(".") - 1)
      Write-Host "Set minor version to '$minorVersion'"
      Write-Host "##vso[task.setvariable variable=Minor]$minorVersion"

- task: PowerShell@2
  displayName: set patch version
  inputs:
    targetType: inline
    script: |
      [string] $patchVersion = "$(branchName)".SubString("$(branchName)".IndexOf(".") + 1).SubString("$(branchName)".IndexOf("."))
      Write-Host "Set patch version to '$patchVersion'"
      Write-Host "##vso[task.setvariable variable=Patch]$patchVersion"

- task: Docker@2
  displayName: build image
  inputs:
    command: build
    arguments: '--build-arg PatPlaceholder=$(NugetFeedAccessToken)'
    dockerfile: src/Services/Andaha.Services.Shopping/Dockerfile
    repository: andaha/services/shopping
    containerRegistry: $(containerRegistryConnection)
    tags: $(imageTag)
    
- task: Docker@2
  displayName: push image
  inputs:
    command: push
    dockerfile: src/Services/Andaha.Services.Shopping/Dockerfile
    repository: andaha/services/shopping
    containerRegistry: $(containerRegistryConnection)
    tags: $(imageTag)