trigger:
  branches:
    include:
      - release/shopping/v*
      - refs/release/shopping/v*

pool:
  vmImage: "windows-latest"

variables:
  containerRegistryConnection: "azure-container-reg-dev-connection"
  imageTag: "$(Major).$(Minor).$(Patch)"
  branchName: "$(Build.SourceBranchName)"

steps:
- task: PowerShell@2
  displayName: read and set major version
  inputs:
    targetType: inline
    script: '##vso[task.setvariable variable=Major]$(branchName).SubString(1, $(branchName).IndexOf(".") - 1)'

- task: PowerShell@2
  displayName: read and set minor version
  inputs:
    targetType: inline
    script: '##vso[task.setvariable variable=Minor]$(branchName).SubString($(branchName).IndexOf(".") + 1).SubString(0, $(branchName).IndexOf(".") - 1)'

- task: PowerShell@2
  displayName: read and set patch version
  inputs:
    targetType: inline
    script: '##vso[task.setvariable variable=Patch]$(branchName).SubString($(branchName).IndexOf(".") + 1).SubString($(branchName).IndexOf("."))'

- task: Docker@2
  displayName: build and push image
  inputs:
    command: buildAndPush
    dockerfile: ../Dockerfile
    containerRegistry: $(containerRegistryConnection)
    tags: $(imageTag)
    